<?php

namespace Tests\Feature;

use Illuminate\Database\QueryException;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Support\Facades\DB;
use Tests\TestCase;

class TransactionTest extends TestCase
{
    /**
     * A basic feature test example.
     */
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DB::delete('delete from products');
        DB::delete('delete from categories');

    }

    public function testTransactionSuccess(): void
    {
        DB::transaction(function (){
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                "GADGET", "Gadget", "Gadget Category", "2020-10-10 10:10:10"
            ]);
            DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                "GADGET2", "Gadget2", "Gadget Category2", "2020-10-10 10:10:10"
            ]);
        });
        $result = DB::select("select * from categories" );
        self::assertCount(2, $result);
    }
    public function testTransactionFailed(): void
    {
        try {
            DB::transaction(function (){
                DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                    "GADGET", "Gadget", "Gadget Category", "2020-10-10 10:10:10"
                ]);
                DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                    "GADGET", "Gadget2", "Gadget Category2", "2020-10-10 10:10:10"
                ]);
            });

        }catch (QueryException $error){

        }
        $result = DB::select("select * from categories" );
        self::assertCount(0, $result);
    }
    public function testManualTransactionSuccces(): void
    {
        try {
            DB::beginTransaction();
            DB::transaction(function (){
                DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                    "GADGET", "Gadget", "Gadget Category", "2020-10-10 10:10:10"
                ]);
                DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                    "GADGET2", "Gadget2", "Gadget Category2", "2020-10-10 10:10:10"
                ]);
            });
            DB::commit();

        }catch (QueryException $error){
            DB::rollBack();

        }
        $result = DB::select("select * from categories" );
        self::assertCount(2, $result);
    }
    public function testManualTransactionFailed(): void
    {
        try {
            DB::beginTransaction();
            DB::transaction(function (){
                DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                    "GADGET", "Gadget", "Gadget Category", "2020-10-10 10:10:10"
                ]);
                DB::insert('insert into categories(id, name, description, created_at) values (?, ?, ? , ?)', [
                    "GADGET", "Gadget2", "Gadget Category2", "2020-10-10 10:10:10"
                ]);
            });
            DB::commit();

        }catch (QueryException $error){
            DB::rollBack();

        }
        $result = DB::select("select * from categories" );
        self::assertCount(0, $result);
    }
}
